name: Build Next.js web application
on: push
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
  lintTest:
    name: Lint Test
    runs-on: ubuntu-latest
    steps:
      - name: Run Linting
        run: echo "Running Linting Tests"
          npm run lint
        env:
          CI: true
  SecurityTest:
    name: Security Test
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security
        run: echo "Running security checks..."
          sleep 1s;
          echo "Running security checks..."
          sleep 1s;
